# logfilename                                           [owner:group]  mode  count  size   when  flags
/Users/koval/Library/Logs/mastra-factory/out.log        koval:staff    644   7      10240  *     NJ
/Users/koval/Library/Logs/mastra-factory/err.log        koval:staff    644   7      10240  *     NJ
/Users/koval/Library/Logs/mastra-factory/colima.log     koval:staff    644   7      10240  *     NJ
/Users/koval/Library/Logs/mastra-factory/colima.err.log koval:staff    644   7      10240  *     NJ
